version: '3'
services:
  postgres: 
    image: 'postgres:latest'
  redis:
    image: 'redis:latest'
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
  api:
    build:
      dockerfile: Dockerfile.dev # there is no need to specify folder (define in context:)
      context: ./server          #use all the files inside this folder to build a image
    volumes:
      - /app/node_modules # inside app folder dont override node_modıles folder.
      - ./server:/app     # reference app dorectory to file and folder inside server folder
                          # every changes inside server will reflect to app folder inside container
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379 # default port for redis
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432 # default port for postgres
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
  worker:
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /app/node_modules
      - ./worker:/app
